### ISSUE TITLE
Registered site variable TimeOfLastFire should be TimeOfLastEvent

### ISSUE THREAD

**Issue by brmiranda** [LANDIS-II-Foundation/Extension-Base-Fire#12]
A RegisteredSiteVar has been added to Base Fire called TimeOfLastFire.  However, to be consistent with other extensions, the name should be TimeOfLastEvent.  Dynamic Fire, Base Wind, Linear Wind and Base and Biomass Harvest all use the naming convention of DisturbanceType.TimeOfLastEvent for the RegisteredSiteVars.  This enables other extensions to be compatible across different extensions of the same type.

For example an extension that wants to use the information about the last fire event should be able to refer to Fire.TimeOfLastEvent and it should work whether the user ran Base Fire or Dynamic Fire.  Currently, the other extension would have to try loading both Fire.TimeOfLastEvent and Fire.TimeOfLastFire and check which one worked to be compatible with both versions of fire.

**Comment by aruzicka555** [comment]
Name changed, pull request submitted to Bruce.
