### ISSUE TITLE
Need to Register Time-Of-Last-Fire

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Base-Fire#8]
This code can duplicate fire-severity code, which is properly registered.

**Comment by aruzicka555** [comment]
Code added, pull request submitted - issue can be closed.

**Comment by bmarron18** [comment]
Does this require a QAQC check since it was completed outside QAQC protocols? In other words, it is just a simple enhancement only?

**Comment by rmscheller** [comment]
No QAQC required as it does not change the behavior of Base Fire.  Any problems would be discovered via the disturbance stand ranking in Base/Biomass Harvest.
